const BASENAME=process.env.REACT_APP_BASENAME||'';
const AUTH_API_BASE_URL=process.env.REACT_APP_AUTH_API_BASE_URL||'';
const API_BASE_URL=process.env.REACT_APP_API_BASE_URL||'';
const BACKEND_ORIGIN=process.env.REACT_APP_BACKEND_ORIGIN||'';
const AES_SECRET=process.env.REACT_APP_AES_SECRET||'';

export { BASENAME,AUTH_API_BASE_URL,API_BASE_URL,BACKEND_ORIGIN,AES_SECRET };